### ISSUE TITLE
Request support for client qBittorrent

### ISSUE THREAD

**Issue by Icemic** [zcqian/tjupt#3]
qBittorrent is an open source BT client, using Qt as its GUI.

It is much better than μTorrents on Windows, including all functions of a BT client, **without any advertisements**.

I am **confused** why you refused to support it (**as an admin of tjupt says**).

Just because only few people using it? If only you refuse to support, fewer people will use it, isn't it?

More Info: http://www.qbittorrent.org/

**Comment by zcqian** [comment]
This issue is less related to the code but more related to the operation of the site. I'd recommend discussing it on the site forums again.

But I'd still like to point out the problems. qBittorrent uses a more recent version of libtorrent, compared to the versions verified to work in the supported clients list. We support libtorrent versions 0.15/0.16, and versions beyond 1.0 seem to have had a version bump. If you are happy to verify that it works as expected (sends correct requests to the tracker, etc.), I believe we could add it.

**Comment by Icemic** [comment]
all right, you can tell me how to verify it, i will try.

yes, i ve suggest that in many way, including forum absolutely, but was replied same as above.

besides, i ve use qTor in bt.neu6.eud.cn, where it works fine.

however, there are several issues remains, why are you close it?

**Comment by zcqian** [comment]
I'm recommending that you discuss this in the forums which is more relevant.

To verify, just capture the request it sends to the trackers. Remove any sensitive information and send it to me personally.
